Version Check
ditadewindita/CodeUSummer2017 pull request #5
Opened 2017-05-24 04:30 UTC by ditadewindita

Added version check feature and more files to .`gitignore` to prevent staging of IDE-specific config files.

Instead of displaying server info as specified in the tutorial, I hashed the info to map to a new Command, which fixed the `Connection rejected` log error when trying to display the server info.

Also downgraded log level to `verbose` to prevent spamming from `Reading from relay...` message, and fixed the spelling in some of the comments :)

2017-05-24 04:36 UTC, kevmo314 commented on src/codeu/chat/client/core/View.java
> +        return new ServerInfo(version);
You can just inline version here:
```
return new ServerInfo(Uuid.SERIALIZER.read(connection.in()));
```

2017-05-24 04:37 UTC, kevmo314 commented on src/codeu/chat/common/ServerInfo.java
> +            version = Uuid.parse(SERVER_VERSION);
Assign directly to this.version, ie

```
try {
   this.version = Uuid.parse(SERVER_VERSION);
} catch(Exception ex) {
  this.version = Uuid.NULL;
  LOG.error(ex, "...");
}

2017-05-24 04:38 UTC, kevmo314 commented on src/codeu/chat/server/Server.java
> +        Uuid.SERIALIZER.write(out, version);
Inline version.

```
Uuid.SERIALIZER.write(out, info.version);
```

2017-05-24 04:39 UTC, kevmo314 requested changes
Code looks good, do you have a test for the version info call?

2017-05-25 01:47 UTC, ditadewindita commented on src/codeu/chat/common/ServerInfo.java
> +            version = Uuid.parse(SERVER_VERSION);
I did that in the beginning, but my compiler complains when I try this with the error: `Variable 'version' might already be assigned to`
I think it has something to do with my class variable (`this.version`), since it's final and final variables can only be assigned to once. The fix was using a temporary non-final variable, but I can just change my class variable to not be final.

2017-05-25 01:57 UTC, kevmo314 commented on src/codeu/chat/common/ServerInfo.java
> +            version = Uuid.parse(SERVER_VERSION);
Ah, I see. You could also do this with a getter instead, ie get rid of `version` and just add a

```
public Uuid getVersion() {
  try {
    return Uuid.parse(SERVER_VERSION);
  } catch(Exception ex) {
    LOG.error(...);
    return Uuid.NULL;
  }
}
```

2017-05-26 01:10 UTC, kevmo314 approved these changes

2017-05-26 02:27 UTC, merged